### ISSUE TITLE
!(.exists) waits the full timeout duration

### ISSUE THREAD

**Issue by matcartmill** [IanKeen/DropBear#12]
Currently `.exists` will wait 5 seconds for the element to exist. When doing `!(.exists)`, it's simply returning the opposite of what the `.exists` matcher will give.

At that point, every `!(.exists)` is guaranteed to take 5 seconds to complete. The user would need to do `!(.exists(waiting: 0))` for every `!` check on exists.

**Comment by IanKeen** [comment]
I suspect I may need to remove the `!` operator and add assertions like `.doesNotExist` instead - otherwise it might not be possible to get the same performance gains

**Comment by IanKeen** [comment]
I have left the `!` operator in as its useful for _most_ assertions. `.exists` is a special case as there's the potential for polling/waiting.. to resolve this I've added an explicit `.doesNotExist` counterpart.
